M48
; DRILL file {KiCad 9.0.2} date 2025-06-08T07:28:39-0600
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-06-08T07:28:39-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.2
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X97.465Y-66.16
X102.315Y-66.16
T2
X97.165Y-63.13
X102.615Y-63.13
M30
