M48
; DRILL file {KiCad 8.0.2} date 2024-07-03T09:30:28-0600
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-07-03T09:30:28-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X3.8372Y-2.6047
X4.0281Y-2.6047
T2
X3.8254Y-2.4854
X4.04Y-2.4854
M30
